-- Add 50+ more questions for each game type including 18+ content
-- This migration adds comprehensive, diverse game content for adult drinking games

-- ============================================
-- TRUTH OR DARE - TRUTH QUESTIONS (50+ new)
-- ============================================

INSERT INTO game_content (game_type, content_type, content, difficulty) VALUES
-- NORMAL TRUTHS
('truth_or_dare', 'truth', 'Bạn có từng giả vờ ngủ để tránh nói chuyện với ai không?', 'easy'),
('truth_or_dare', 'truth', 'Điều gì khiến bạn cảm thấy tự ti nhất?', 'easy'),
('truth_or_dare', 'truth', 'Bạn đã bao giờ unfriend ai vì ghen tị chưa?', 'easy'),
('truth_or_dare', 'truth', 'Thói quen xấu nhất mà bạn đang cố giấu?', 'easy'),
('truth_or_dare', 'truth', 'Bạn có từng nói dối trong cuộc phỏng vấn xin việc không?', 'easy'),
('truth_or_dare', 'truth', 'Ai là người bạn hay stalk nhất trên mạng xã hội?', 'easy'),
('truth_or_dare', 'truth', 'Bạn có từng làm điều gì để gây ấn tượng với crush không?', 'easy'),
('truth_or_dare', 'truth', 'Điều gì bạn luôn nghĩ nhưng không dám nói?', 'medium'),
('truth_or_dare', 'truth', 'Bạn có từng ước mình là người khác không? Ai?', 'medium'),
('truth_or_dare', 'truth', 'Lần cuối cùng bạn khóc là vì chuyện gì?', 'medium'),
('truth_or_dare', 'truth', 'Bạn sẽ làm gì nếu có 1 tỷ đồng ngay bây giờ?', 'easy'),
('truth_or_dare', 'truth', 'Ai trong nhóm này bạn nghĩ sẽ thành công nhất?', 'medium'),
('truth_or_dare', 'truth', 'Bạn có từng cảm thấy bị phản bội bởi bạn thân không?', 'medium'),
('truth_or_dare', 'truth', 'Điều bí mật nào về gia đình bạn chưa ai biết?', 'hard'),
('truth_or_dare', 'truth', 'Bạn có từng ước người khác thất bại không? Ai?', 'hard'),
('truth_or_dare', 'truth', 'Nếu có thể xóa 1 ký ức, bạn sẽ xóa gì?', 'hard'),
('truth_or_dare', 'truth', 'Bạn đã làm điều tệ nhất gì khi say?', 'hard'),
('truth_or_dare', 'truth', 'Người bạn ghét nhất trong đời là ai? Vì sao?', 'hard'),
('truth_or_dare', 'truth', 'Bạn có từng lợi dụng tình cảm của ai không?', 'hard'),
('truth_or_dare', 'truth', 'Điều gì bạn sẽ không bao giờ tha thứ?', 'hard'),

-- SPICY TRUTHS (18+)
('truth_or_dare', 'truth', 'Tần suất bạn "tự sướng" là bao nhiêu?', '18+'),
('truth_or_dare', 'truth', 'Bạn thích tư thế nào nhất khi làm tình?', '18+'),
('truth_or_dare', 'truth', 'Điều gì khiến bạn "on" nhất?', '18+'),
('truth_or_dare', 'truth', 'Bạn có từng làm với người không biết tên không?', '18+'),
('truth_or_dare', 'truth', 'Fantasy nào bạn muốn thực hiện nhưng chưa dám?', '18+'),
('truth_or_dare', 'truth', 'Bạn đã từng xem phim 18+ thể loại gì kỳ lạ nhất?', '18+'),
('truth_or_dare', 'truth', 'Số lần bạn làm tình nhiều nhất trong 1 ngày là bao nhiêu?', '18+'),
('truth_or_dare', 'truth', 'Bạn có từng gọi nhầm tên khi "lên đỉnh" không?', '18+'),
('truth_or_dare', 'truth', 'Điều gì khiến bạn "tắt máy" ngay lập tức khi đang làm?', '18+'),
('truth_or_dare', 'truth', 'Bạn có thích được dominance hay submissive?', '18+'),
('truth_or_dare', 'truth', 'Địa điểm công cộng nào bạn muốn thử làm tình nhất?', '18+'),
('truth_or_dare', 'truth', 'Bạn có từng "finish" quá nhanh và xấu hổ không?', '18+'),
('truth_or_dare', 'truth', 'Ai trong phòng này có body hấp dẫn nhất theo bạn?', '18+'),
('truth_or_dare', 'truth', 'Bạn thích foreplay như thế nào?', '18+'),
('truth_or_dare', 'truth', 'Điều gì partner cũ làm tốt nhất trên giường?', '18+'),
('truth_or_dare', 'truth', 'Bạn có từng giả vờ "đến" để kết thúc sớm không?', '18+'),
('truth_or_dare', 'truth', 'Bạn nghĩ mình giỏi oral sex không? Tự đánh giá đi', '18+'),
('truth_or_dare', 'truth', 'Điều kỳ lạ nhất bạn thấy khi xem phim 18+ là gì?', '18+'),
('truth_or_dare', 'truth', 'Bạn có muốn thử anal không? Đã thử chưa?', '18+'),
('truth_or_dare', 'truth', 'Size có quan trọng không? Thật lòng đi', '18+'),

-- ============================================
-- TRUTH OR DARE - DARE CHALLENGES (50+ new)
-- ============================================

-- NORMAL DARES
('truth_or_dare', 'dare', 'Nhắn tin cho 5 người khác nhau "Tao đang nghĩ về mày"', 'easy'),
('truth_or_dare', 'dare', 'Đăng story "Đang tìm người yêu, inbox nhanh"', 'easy'),
('truth_or_dare', 'dare', 'Gọi điện cho người cuối cùng call và hát Happy Birthday', 'easy'),
('truth_or_dare', 'dare', 'Làm 10 cái jumping jack ngay bây giờ', 'easy'),
('truth_or_dare', 'dare', 'Nói giọng miền khác trong 3 phút tới', 'easy'),
('truth_or_dare', 'dare', 'Để người bên cạnh kiểm tra tin nhắn gần nhất của bạn', 'medium'),
('truth_or_dare', 'dare', 'Gọi điện cho bạn thân và nói "Tao yêu mày" rồi cúp ngay', 'medium'),
('truth_or_dare', 'dare', 'Mô phỏng tiếng động vật do người khác chọn trong 1 phút', 'medium'),
('truth_or_dare', 'dare', 'Đổi avatar Facebook thành ảnh xấu trong 24h', 'medium'),
('truth_or_dare', 'dare', 'Để ai đó viết status lên Facebook của bạn', 'medium'),
('truth_or_dare', 'dare', 'Uống 2 shot liên tiếp không được nhăn mặt', 'hard'),
('truth_or_dare', 'dare', 'Gọi điện cho crush và nói "Anh/Em thích bạn lắm"', 'hard'),
('truth_or_dare', 'dare', 'Làm 20 cái squat trong khi hát', 'hard'),
('truth_or_dare', 'dare', 'Để nhóm chọn người và bạn phải ôm họ 30 giây', 'hard'),
('truth_or_dare', 'dare', 'Cho số điện thoại cho người lạ đầu tiên gặp ngoài đường', 'hard'),

-- SPICY DARES (18+)
('truth_or_dare', 'dare', 'Thì thầm điều gợi cảm nhất bạn có thể nghĩ ra vào tai người bên cạnh', '18+'),
('truth_or_dare', 'dare', 'Làm tiếng rên như trong phim 18+ trong 20 giây', '18+'),
('truth_or_dare', 'dare', 'Tả lại chi tiết lần làm tình gần nhất của bạn', '18+'),
('truth_or_dare', 'dare', 'Mô phỏng động tác yêu thích của bạn trên giường (có quần áo)', '18+'),
('truth_or_dare', 'dare', 'Massage vai cho người đối diện trong 2 phút', '18+'),
('truth_or_dare', 'dare', 'Cởi 1 món đồ (ngoài giày/vớ) và để đến hết game', '18+'),
('truth_or_dare', 'dare', 'Liếm môi một cách gợi cảm trong 10 giây', '18+'),
('truth_or_dare', 'dare', 'Gửi tin nhắn "Đêm nay rảnh không?" cho người cuối chat', '18+'),
('truth_or_dare', 'dare', 'Hôn má người mà nhóm chọn', '18+'),
('truth_or_dare', 'dare', 'Nói dirty talk với người đối diện trong 30 giây', '18+'),
('truth_or_dare', 'dare', 'Để ai đó trong nhóm xoa lưng cho bạn 1 phút', '18+'),
('truth_or_dare', 'dare', 'Tạo dáng sexy nhất bạn có thể và chụp ảnh', '18+'),
('truth_or_dare', 'dare', 'Gửi voice message "Em nhớ anh" cho người ngẫu nhiên', '18+'),
('truth_or_dare', 'dare', 'Đóng giả cảnh hôn trong phim với người được chọn', '18+'),
('truth_or_dare', 'dare', 'Ngồi lên đùi người đối diện trong 1 vòng chơi', '18+'),

-- ============================================
-- NEVER HAVE I EVER (50+ new)
-- ============================================

-- NORMAL
('never_have_i_ever', 'question', 'Tôi chưa bao giờ giả vờ bận để không đi chơi với ai', 'easy'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ ăn đồ ăn đã rơi xuống đất', 'easy'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ quên tên người vừa mới quen', 'easy'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ reply tin nhắn rồi quên gửi', 'easy'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ tự khen mình trước gương', 'easy'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ khóc vì một người không xứng đáng', 'medium'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ làm điều ngu ngốc chỉ để gây ấn tượng', 'medium'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ theo dõi người yêu cũ trên mạng', 'medium'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ nói "Tao đến rồi" khi còn đang ở nhà', 'easy'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ giả ốm để được nghỉ làm/học', 'easy'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ quên sinh nhật người quan trọng', 'medium'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ bị đuổi việc hoặc suýt bị đuổi', 'medium'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ đi bar/club một mình', 'medium'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ say đến mức không nhớ gì', 'hard'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ làm điều gì vi phạm pháp luật', 'hard'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ cắt đứt liên lạc với ai mà không giải thích', 'hard'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ tiêu hết tiền lương trong 1 tuần', 'medium'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ hối tiếc vì đã yêu ai đó', 'hard'),

-- SPICY (18+)
('never_have_i_ever', 'question', 'Tôi chưa bao giờ gửi ảnh sexy cho người lạ', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ làm tình khi có người khác ở gần', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ bị bắt gặp khi đang làm chuyện ấy', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ dùng Tinder hoặc app hẹn hò', 'medium'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ có one-night-stand với người quen', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ làm tình trong xe hơi', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ xem phim 18+ với người khác', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ có fantasy về người trong nhóm này', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ làm tình lúc say xỉn', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ thử đồ chơi người lớn', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ gửi/nhận sexting lúc đang ở chỗ làm', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ làm tình vào buổi sáng sớm', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ thử bondage hoặc BDSM', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ làm tình ở khách sạn', 'hard'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ có nhiều hơn 1 partner trong 1 tháng', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ làm tình với người hơn mình 10+ tuổi', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ làm tình trong toilet công cộng', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ quay video lúc làm tình', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ thử threesome', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ làm tình với sếp hoặc đồng nghiệp', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ nghĩ về người khác khi đang làm tình', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ dùng dating app chỉ để hookup', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ nhận được hoặc gửi dick pic', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ làm tình khi đang có period', '18+'),
('never_have_i_ever', 'question', 'Tôi chưa bao giờ thử role-play khi làm tình', '18+'),

-- ============================================
-- CHALLENGES (50+ new)
-- ============================================

-- EASY
('challenge', 'action', 'Hát 1 đoạn của bài hát yêu thích', 'easy'),
('challenge', 'action', 'Kể 1 chuyện cười trong 30 giây', 'easy'),
('challenge', 'action', 'Bắt chước giọng nói của ai đó trong nhóm', 'easy'),
('challenge', 'action', 'Nói 1 bí mật nhỏ về bản thân', 'easy'),
('challenge', 'action', 'Làm mặt hài hước và chụp ảnh', 'easy'),
('challenge', 'action', 'Nhảy theo bài hát trong 30 giây', 'easy'),
('challenge', 'action', 'Gọi điện và nói "Tao yêu mày" rồi cúp', 'easy'),
('challenge', 'action', 'Tự giới thiệu bằng cách hát', 'easy'),

-- MEDIUM
('challenge', 'action', 'Làm 15 cái push-up trong 1 phút', 'medium'),
('challenge', 'action', 'Uống hết ly của bạn trong 10 giây', 'medium'),
('challenge', 'action', 'Nhắn tin thả thính cho người cuối cùng chat', 'medium'),
('challenge', 'action', 'Gọi điện cho người ngẫu nhiên và hỏi "Mày có đói không?"', 'medium'),
('challenge', 'action', 'Đăng story với caption do nhóm chọn', 'medium'),
('challenge', 'action', 'Freestyle rap về chủ đề nhóm chọn trong 1 phút', 'medium'),
('challenge', 'action', 'Đọc tin nhắn gần nhất của bạn cho cả nhóm nghe', 'medium'),
('challenge', 'action', 'Để người bên cạnh đổi wallpaper điện thoại của bạn', 'medium'),
('challenge', 'action', 'Gọi đặt đồ ăn bằng giọng buồn cười', 'medium'),
('challenge', 'action', 'Diễn kịch 1 mình về chủ đề tình yêu trong 1 phút', 'medium'),

-- HARD
('challenge', 'action', 'Uống 3 shot liên tiếp không nghỉ', 'hard'),
('challenge', 'action', 'Gọi điện cho người yêu cũ và xin lỗi', 'hard'),
('challenge', 'action', 'Để nhóm hỏi bất cứ câu hỏi nào và phải trả lời thật', 'hard'),
('challenge', 'action', 'Đi ra ngoài và xin số điện thoại người lạ', 'hard'),
('challenge', 'action', 'Cho người khác đọc 10 tin nhắn gần nhất', 'hard'),
('challenge', 'action', 'Chống đẩy 30 cái hoặc uống 3 shot', 'hard'),
('challenge', 'action', 'Để nhóm post bất cứ gì lên story của bạn', 'hard'),
('challenge', 'action', 'Gọi điện cho bố mẹ và nói bạn đang say', 'hard'),
('challenge', 'action', 'Hét to "Tao đang say!" ở nơi công cộng', 'hard'),
('challenge', 'action', 'Tỏ tình với người ngồi đối diện (giả vờ)', 'hard'),

-- EXTREME/18+
('challenge', 'action', 'Body shot từ bụng người được nhóm chọn', '18+'),
('challenge', 'action', 'Massage lưng cho người bên phải trong 2 phút', '18+'),
('challenge', 'action', 'Ngồi lên đùi người được chọn trong 1 vòng', '18+'),
('challenge', 'action', 'Để người khác whisper điều nóng bỏng vào tai bạn', '18+'),
('challenge', 'action', 'Làm lap dance cho người được nhóm vote', '18+'),
('challenge', 'action', 'Hôn má 3 người trong nhóm', '18+'),
('challenge', 'action', 'Strip poker: Oẳn tù tì, thua cởi 1 món', '18+'),
('challenge', 'action', 'Mô tả chi tiết bạn muốn làm gì với crush', '18+'),
('challenge', 'action', 'Gửi tin nhắn flirty cho người cuối cùng chat', '18+'),
('challenge', 'action', 'Thì thầm điều sexy nhất vào tai người bên cạnh', '18+'),

-- ============================================
-- MOST LIKELY TO (50+ new)
-- ============================================

('most_likely_to', 'question', 'Ai có khả năng say đầu tiên?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng ngủ gật khi đang party?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng trở thành triệu phú?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng kết hôn đầu tiên?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng vẫn F.A sau 10 năm?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng làm điều gì đó viral trên mạng?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng sống sót khi zombie apocalypse?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng đánh mất điện thoại ở đây?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng khóc vì phim lãng mạn?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng ăn cay nhất?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng trở thành influencer?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng quên tên crush?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng nói dối giỏi nhất?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng bị bắt vì làm điều gì đó ngu ngốc?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng chi tiền hoang phí nhất?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng có nhiều người theo đuổi nhất?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng làm CEO của công ty lớn?', 'easy'),
('most_likely_to', 'question', 'Ai có khả năng tham gia reality show?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng viết sách về đời mình?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng có affair sau khi kết hôn?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng cãi nhau với bồ ở nơi công cộng?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng bị friend-zone nhiều nhất?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng ghost người sau date đầu tiên?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng date người hơn 15 tuổi?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng làm sugar baby?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng có one-night-stand với người lạ?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng quay lại với ex?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng nhắn tin ex lúc say?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng làm chuyện 18+ ở nơi công cộng?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng có 3-some trước?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng gửi nudes cho người yêu?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng làm tình vào ngày đầu tiên gặp?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng cheat on partner?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng bị catfish trên dating app?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng stalk ex nhiều nhất?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng date 2 người cùng lúc?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng làm điều gì đó hối hận khi say?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng bị đuổi khỏi bar/club?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng say và khóc về người yêu cũ?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng text bạn trai/gái của bạn mình?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng làm điều scandal nhất?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng có crush bí mật với ai đó trong nhóm?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng kết hôn với người giàu vì tiền?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng ly hôn đầu tiên?', 'hard'),
('most_likely_to', 'question', 'Ai có khả năng nuôi nhiều mèo và sống một mình?', 'medium'),
('most_likely_to', 'question', 'Ai có khả năng trở thành player?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng bắt cá nhiều tay?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng làm stripper nếu cần tiền?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng bán nudes online?', '18+'),
('most_likely_to', 'question', 'Ai có khả năng làm OnlyFans?', '18+'),

-- ============================================
-- CATEGORIES (Chủ đề kể tên) - 30+ new
-- ============================================

('categories', 'topic', 'Các loại bia nổi tiếng', 'easy'),
('categories', 'topic', 'Các loại cocktail', 'easy'),
('categories', 'topic', 'Các loại rượu mạnh', 'easy'),
('categories', 'topic', 'Các thương hiệu thời trang', 'easy'),
('categories', 'topic', 'Các bộ phim Marvel', 'easy'),
('categories', 'topic', 'Các ca sĩ Việt Nam nổi tiếng', 'easy'),
('categories', 'topic', 'Các quốc gia ở Châu Âu', 'easy'),
('categories', 'topic', 'Các món ăn Việt Nam', 'easy'),
('categories', 'topic', 'Các loại trà sữa', 'easy'),
('categories', 'topic', 'Các app hẹn hò', 'medium'),
('categories', 'topic', 'Các tư thế yoga', 'medium'),
('categories', 'topic', 'Các bài hát Vpop nổi tiếng', 'easy'),
('categories', 'topic', 'Các thành phố ở Việt Nam', 'easy'),
('categories', 'topic', 'Các loại xe hơi', 'medium'),
('categories', 'topic', 'Các loại crypto', 'hard'),
('categories', 'topic', 'Các phim 18+ nổi tiếng (không cần chi tiết)', '18+'),
('categories', 'topic', 'Các tư thế làm tình (tên tiếng Anh)', '18+'),
('categories', 'topic', 'Các từ dirty talk bằng tiếng Anh', '18+'),
('categories', 'topic', 'Các vùng nhạy cảm trên cơ thể', '18+'),
('categories', 'topic', 'Các loại đồ chơi người lớn', '18+'),
('categories', 'topic', 'Các fetish phổ biến', '18+'),
('categories', 'topic', 'Các cách flirt với crush', 'medium'),
('categories', 'topic', 'Các lý do chia tay', 'medium'),
('categories', 'topic', 'Các red flag trong mối quan hệ', 'medium'),
('categories', 'topic', 'Các dating apps phổ biến', 'medium'),
('categories', 'topic', 'Các loại hình thể thao', 'easy'),
('categories', 'topic', 'Các loại nhạc cụ', 'easy'),
('categories', 'topic', 'Các thương hiệu điện thoại', 'easy'),
('categories', 'topic', 'Các mạng xã hội', 'easy'),
('categories', 'topic', 'Các game mobile phổ biến', 'easy')

ON CONFLICT DO NOTHING;
